export const FETCH_STORE_DATA = 'FETCH_STORE_DATA';
export const ADD_STORE_ITEM = 'ADD_STORE_ITEM';
export const UPDATE_STORE_ITEM = 'UPDATE_STORE_ITEM';
export const DELETE_STORE_ITEM = 'DELETE_STORE_ITEM';
export const UPDATE_STORE_ITEM_AMOUNT = 'UPDATE_STORE_ITEM_AMOUNT';

export const FETCH_SUBSET_DATA = 'FETCH_SUBSET_DATA';
export const CHANGE_TO_CURRENT_STATE = 'CHANGE_TO_CURRENT_STATE';

export const FETCH_RECEIPTS = 'FETCH_RECEIPTS';
export const FETCH_RECEIPT = 'FETCH_RECEIPT';
export const CHANGE_SELECTED_RECEIPT = 'CHANGE_SELECTED_RECEIPT';
export const ADD_RECEIPT_HEADER = 'ADD_RECEIPT_HEADER';
export const UPDATE_RECEIPT_HEADER = 'UPDATE_RECEIPT_HEADER';
export const ADD_RECEIPT_ITEM = 'ADD_RECEIPT_ITEM';
export const DELETE_RECEIPT_ITEM = 'DELETE_RECEIPT_ITEM';
export const DELETE_RECEIPT = 'DELETE_RECEIPT';

export const FETCH_ISSUE_CARDS = 'FETCH_ISSUE_CARDS';
export const FETCH_ISSUE_CARD = 'FETCH_ISSUE_CARD';
export const CHANGE_SELECTED_ISSUE_CARD = 'CHANGE_SELECTED_ISSUE_CARD';
export const ADD_ISSUE_CARD_HEADER = 'ADD_ISSUE_CARD_HEADER';
export const UPDATE_ISSUE_CARD_HEADER = 'UPDATE_ISSUE_CARD_HEADER';
export const ADD_ISSUE_CARD_ITEM = 'ADD_ISSUE_CARD_ITEM';
export const DELETE_ISSUE_CARD_ITEM = 'DELETE_ISSUE_CARD_ITEM';
export const DELETE_ISSUE_CARD = 'DELETE_ISSUE_CARD';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_INITIALIZED = 'REQUEST_INITIALIZED';
export const REQUEST_SUCCEEDED = 'REQUEST_SUCCEEDED';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';
export const SET_ACTIVE_LINK = 'SET_ACTIVE_LINK';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
